repair water-slice Commit 1
intime-global/water-tracker-frontend pull request #65
Opened 2024-12-16 12:38 UTC by Dava1991

2024-12-16 16:35 UTC, ustym-karpiuk commented on src/components/AddWaterModal/AddWaterModal.jsx
>  import React, { useState, useEffect } from 'react';
React

2024-12-17 20:26 UTC, ReshetS requested changes

2024-12-17 20:26 UTC, ReshetS commented on src/redux/month/monthApi.js
> +const response = await axiosInstance.patch('/user/', data);
Це, мабуть, тут зайве?

2024-12-17 20:26 UTC, ReshetS commented on src/redux/water/waterApi.js
> +const response = await axiosInstance.patch('/user/', data);
'response' is assigned a value but never used.

Знову зкопіпастив зайве

2024-12-17 20:26 UTC, ReshetS commented on src/redux/water/waterApi.js
> +    const { data } = await api.patch(`/water/${body.id}`, {
'api' is not defined.

2024-12-17 20:32 UTC, closed without merging