add component dailyNorma+modal
intime-global/water-tracker-frontend pull request #68
Opened 2024-12-16 14:29 UTC by Taisiia-Mazur

2024-12-16 17:07 UTC, ustym-karpiuk commented on src/components/DeilyNormaModal/DeilyNormaModal.module.css
![image](https://github.com/user-attachments/assets/7a31086d-b2a2-4f62-9237-3a858be8d5e8)

2024-12-16 17:08 UTC, ustym-karpiuk commented on src/components/DailyNorma/DailyNorma.module.css
![image](https://github.com/user-attachments/assets/4d7cdd37-921a-4f23-9d16-65d781fa0176)
--**primary**-color-white

2024-12-17 20:15 UTC, ReshetS requested changes

2024-12-17 20:15 UTC, ReshetS commented on src/components/DailyNorma/DailyNorma.jsx
> +          </ModalContainer>
Двічі огортаєш у ModalContainer

2024-12-19 14:51 UTC, closed without merging